services:
  sast-dashboard:
    container_name: sast-dashboard
    image: node:26.2.0-alpine3.23
    working_dir: /app
    command: sh -c "npm install -g pnpm@11.1.3 && pnpm i && pnpm run dev"
    env_file:
      - .env.development
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - sast-network

networks:
  sast-network:
    driver: bridge