FROM node:26.2.0-slim

RUN npm install -g corepack && corepack enable && corepack prepare pnpm@11.1.3 --activate
RUN corepack enable && corepack prepare pnpm@11.1.3 --activate

ENV PNPM_HOME=/home/node/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

WORKDIR /app
RUN mkdir -p /app/node_modules && chown -R node:node /app
USER node