services:
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      - CI=true
      - PNPM_HOME=/home/node/.local/share/pnpm
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
    command: sh -c "pnpm config set store-dir /home/node/.local/share/pnpm-store && pnpm i && pnpm run dev"
    env_file:
      - .env.development
    volumes:
      - ./:/app
      - dashboard_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - dashboard-network

volumes:
  dashboard_node_modules:

networks:
  dashboard-network:
    driver: bridge