services:
  sast-dashboard:
    container_name: sast-dashboard
    image: node:22.15.0-alpine3.21
    working_dir: /app
    command: sh -c "npm install -g pnpm@10.9.0 && pnpm i && pnpm run dev"
    env_file:
      - .env.development
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - sast-network

networks:
  sast-network:
    driver: bridge