#!/bin/bash

docker login && docker build --build-arg NEXT_PUBLIC_BASE_URL=https://sast-dashboard.dumbledore.dev -t viniroveran/sast-dashboard:latest . && docker push viniroveran/sast-dashboard:latest